// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsuKVlJeSXWq3VCShcB35ENdIso7beJeM',
    appId: '1:765759093917:web:bea1c2b4925eb42f6ae874',
    messagingSenderId: '765759093917',
    projectId: 'mapd1234',
    authDomain: 'mapd1234.firebaseapp.com',
    storageBucket: 'mapd1234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnJBrd-Gm4T0ljaKoE5lTFJw0wfwsxSXg',
    appId: '1:765759093917:android:8e6ec28b38f134e76ae874',
    messagingSenderId: '765759093917',
    projectId: 'mapd1234',
    storageBucket: 'mapd1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeo_NKDJ63NxcbIZsEoMCC9HOPt3Qb6a0',
    appId: '1:765759093917:ios:6f7d1c37f848dfd36ae874',
    messagingSenderId: '765759093917',
    projectId: 'mapd1234',
    storageBucket: 'mapd1234.firebasestorage.app',
    iosBundleId: 'com.example.mapd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeo_NKDJ63NxcbIZsEoMCC9HOPt3Qb6a0',
    appId: '1:765759093917:ios:6f7d1c37f848dfd36ae874',
    messagingSenderId: '765759093917',
    projectId: 'mapd1234',
    storageBucket: 'mapd1234.firebasestorage.app',
    iosBundleId: 'com.example.mapd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsuKVlJeSXWq3VCShcB35ENdIso7beJeM',
    appId: '1:765759093917:web:54efc41cb22e3d1b6ae874',
    messagingSenderId: '765759093917',
    projectId: 'mapd1234',
    authDomain: 'mapd1234.firebaseapp.com',
    storageBucket: 'mapd1234.firebasestorage.app',
  );
}
